<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestaurantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $restaurants = [
            [
                'name' => 'Nhà hàng ABC',
                'address' => '123 Đường A, Quận 1, TP.HCM',
                'introduction' => 'Nhà hàng sang trọng với không gian thoáng đãng, phục vụ các món ăn Âu và Á.',
                'image_url' => 'https://media-cdn.tripadvisor.com/media/photo-s/15/c5/84/65/khong-gian-nha-hang-vu.jpg',
                'type_id' => 1,
                'number_of_tables' => 20,
                'user_id' => 1,
                'rating_avg' => 4.5,
                'status' => 1,
                'opening_time' => '10:00:00',
                'closing_time' => '22:00:00',
                'legality' => 1,
                'city_id' => 2,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng XYZ',
                'address' => '456 Đường B, Quận 2, TP.HCM',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://cdn.tgdd.vn/Files/2020/11/24/1308899/5-nha-hang-quan-an-tay-sang-trong-nhat-o-quan-7-202206031045018740.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 2,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng LMN',
                'address' => '789 Đường C, Quận 3, TP.HCM',
                'introduction' => 'Nhà hàng phục vụ các món ăn Trung Hoa, đặc trưng của nền ẩm thực đông anh.',
                'image_url' => 'https://cdn.pastaxi-manager.onepas.vn/content/uploads/articles/lentkdau/cachbotritoiuukhonggian/2.jpg',
                'type_id' => 3,
                'number_of_tables' => 25,
                'user_id' => 3,
                'rating_avg' => 3.5,
                'status' => 1,
                'opening_time' => '11:00:00',
                'closing_time' => '23:00:00',
                'legality' => 1,
                'city_id' => 2,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng PQR',
                'address' => '246 Đường D, Quận 4, TP.HCM',
                'introduction' => 'Nhà hàng phục vụ các món ăn Hàn Quốc, sự kết hợp tinh tế giữa nguyên liệu và gia vị.',
                'image_url' => 'https://amthucmaison.com/wp-content/uploads/2019/04/khong-gian-trong-nha-nha-hang-san-ho-do-1.jpg',
                'type_id' => 4,
                'number_of_tables' => 15,
                'user_id' => 4,
                'rating_avg' => 4.5,
                'status' => 1,
                'opening_time' => '10:30:00',
                'closing_time' => '22:30:00',
                'legality' => 1,
                'city_id' => 2,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Mèo',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://luanvanviet.com/wp-content/uploads/2020/06/hinh-anh-khai-niem-nha-hang-la-gi-2.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Minh Tam',
                'address' => 'Bạch Mai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://dolcehanoigoldenlake.com/wp-content/uploads/2020/01/goden-lake-palace-1.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Thiên Thần',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://media-cdn-v2.laodong.vn/Storage/NewsPortal/2022/8/17/1081922/278672363_3814757561-01.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 3,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Biển Khơi',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://ipos.vn/wp-content/uploads/2021/10/bantaicuahang.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Tây Bắc',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://digiticket.vn/blog/wp-content/uploads/2021/06/131639538_2792447981023098_1241503001126953588_n.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Núi Đồi',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://goldencoto.vn/wp-content/uploads/2022/02/nha-hang-sua-co-to-13.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Bún Quê',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://hotelcareers.vn/wp-content/uploads/2020/12/quy-trinh-phuc-vu-nha-hang.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Mắm Muối',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://ecode.com.vn/wp-content/uploads/2020/10/1-8.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Đại Dương',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://toplist.vn/images/800px/french-grill-jw-marriott-hotel-hanoi-517635.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Sơn Động',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://statics.vincom.com.vn/xu-huong/image8-1667284358.png',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Hồng Thái',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://nld.mediacdn.vn/291774122806476800/2022/3/3/g1-16462996251361955713708.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Mẹ Tám',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://cafefcdn.com/203337114487263232/2023/1/15/photo-16-1673757793928457134081.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Gạo tẻ',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://anviethouse.vn/wp-content/uploads/2021/12/Thiet-ke-nha-hang-Han-Quoc-2-6.png',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Trang Hi',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://tadiha.com/pictures/picfullsizes/2022/11/02/ems1667366708.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Nếp Cẩm',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://nhahangnoisonghuong.com/wp-content/uploads/2021/03/03-500x330.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Sao chổi',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://tamsusaigon.com/wp-content/uploads/2022/12/nha-hang-ben-song-o-sai-gon.png',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Bình Gold',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://blog.dktcdn.net/files/kinh-doanh-nha-hang-5.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Booman',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://www.cet.edu.vn/wp-content/uploads/2018/07/mo-nha-hang.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Độ tộc',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://dulichlive.com/thai-lan/wp-content/uploads/sites/4/2019/09/Nha-hang-ngon-noi-tieng-o-Pattaya-06.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Chuột',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://ik.imagekit.io/tvlk/blog/2018/10/nha-hang-mon-viet-34.jpg?tr=dpr-2,w-675',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Bí Đỏ',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://vnhgroup.vn/Uploads/Images/thiet-ke-nha-hang.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Mướp Đắng',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://reviewvilla.vn/wp-content/uploads/2022/05/nha-hang-phu-quoc-17-1024x546.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Đậu Biếc',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://baosonparadise.vn/Uploads/images/z4198814718942_d5a4c788b25fcb1c4e15bde3eda27fe3(2).jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
            [
                'name' => 'Nhà hàng Gà Ri',
                'address' => 'Minh Khai, Hai Bà Trưng, Hà Nội',
                'introduction' => 'Nhà hàng chuyên phục vụ các món ăn Việt Nam, tinh hoa của ẩm thực đất nước.',
                'image_url' => 'https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_3358,h_2239/https://paoquan.vn/wp-content/uploads/2020/09/2b1.jpg',
                'type_id' => 2,
                'number_of_tables' => 30,
                'user_id' => 2,
                'rating_avg' => 4.0,
                'status' => 1,
                'opening_time' => '08:00:00',
                'closing_time' => '21:00:00',
                'legality' => 1,
                'city_id' => 1,
                'updated_at' => now(),
                'created_at' => now()
            ],
        ];
        DB::table('restaurants')->insert($restaurants);
    }
}
